spring:
  data:
    mongodb:
      host: 192.168.0.111 #指定MongoDB服务地址
      port: 27017 #指定端口，默认就为27017
      database: itheima #指定使用的数据库(集合)
      authentication-database: admin # 登录认证的逻辑库名
      username: admin #用户名
      password: admin #密码

