server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.56.95.151:3307/springboot?serverTimezone=UTC
      username: root
      password: zxcvbnm1


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_   # 表前缀
      id-type: auto  # 数据库的自增策略。
