server:
  port: 80

## activemq
#spring:
#  activemq:
#    broker-url: tcp://192.168.0.111:61616  # 连接地址
#  jms:
#    template:
#      default-destination: itheima
#    pub-sub-domain: true  # 如果不设置默认是false，代表点对点模型。设置为true就是广播模型


## rabbitmq
#spring:
#  rabbitmq:
#    host: 192.168.0.111
#    port: 5672


## rocketmq
#rocketmq:
#  name-server: 192.168.0.111:9876
#  producer:  # 生产者
#    group: group_rocketmq  # 自定义组名


# kafka
spring:
  kafka:
    bootstrap-servers: 192.168.0.111:9092
    consumer:
      group-id: order
