
# 定时任务相关配置  可选
spring:
  task:
    scheduling:
      pool:
        size: 1  # 任务调度线程池大小，默认 1
    execution:
      thread-name-prefix: spring_task_  # 调度线程名称前缀，默认scheduling-
      shutdown:
        await-termination: false  # 线程池关闭时等待所有任务完成
        await-termination-period: 10s  # 调度线程关闭前最大等待时间，确保最后一定关闭
