# 开启debug模式，输出调试信息，常用于检查系统运行状况
#debug: true

# 设置日志级别，root表示根节点，即整体应用日志级别
logging:
  # 设置分组，对某个组设置日志级别
  group:
    fenzu1: org.example.springboot.service, org.example.springboot.dao
    fenzu2: org.example.springboot.controller
  level:
#    root: info
#    org.example.springboot.controller: debug  # 设置某个包的日志级别
    fenzu2: error  # 对某个组设置日志级别


  # 设置日志输出格式
#  pattern:
#    console: "%d [%p] [%t] %m%n"

  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB # 设置文件最大多大
      file-name-pattern: server.%d.%i.log  # 设置文件名。比如server.2023-05-27.0.log   %i代表第几个


